import { MarketData } from '../types';

/**
 * Pacifica API Client
 * Handles order creation and market data fetching
 */
export class PacificaClient {
  private baseUrl = 'https://test-api.pacifica.fi/api/v1';

  constructor() {
    // No API key needed - signing is done by wallet
  }

  /**
   * Create market order
   * Signature must be generated by wallet on frontend
   */
  async createMarketOrder(
    walletAddress: string,
    symbol: string,
    side: 'bid' | 'ask',
    amount: string,
    signature: string,
    timestamp: number,
    builderCode?: string
  ): Promise<any> {
    const path = '/orders/create_market';
    const body = {
      account: walletAddress,
      agent_wallet: null,
      signature,
      timestamp,
      expiry_window: 30000,
      symbol,
      side,
      amount,
      slippage_percent: '0.5',
      reduce_only: false,
      builder_code: builderCode,
    };

    try {
      const response = await fetch(`${this.baseUrl}${path}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });

      if (!response.ok) {
        const error = await response.text();
        throw new Error(`Pacifica API error: ${response.statusText} - ${error}`);
      }

      return await response.json();
    } catch (error) {
      console.error('[PacificaClient] Error creating market order:', error);
      throw error;
    }
  }

  /**
   * Create limit order
   * Signature must be generated by wallet on frontend
   */
  async createLimitOrder(
    walletAddress: string,
    symbol: string,
    side: 'bid' | 'ask',
    amount: string,
    price: string,
    signature: string,
    timestamp: number,
    builderCode?: string
  ): Promise<any> {
    const path = '/orders/create';
    const body = {
      account: walletAddress,
      agent_wallet: null,
      signature,
      timestamp,
      expiry_window: 30000,
      symbol,
      side,
      amount,
      price,
      tif: 'GTC',
      reduce_only: false,
      builder_code: builderCode,
    };

    try {
      const response = await fetch(`${this.baseUrl}${path}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });

      if (!response.ok) {
        const error = await response.text();
        throw new Error(`Pacifica API error: ${response.statusText} - ${error}`);
      }

      return await response.json();
    } catch (error) {
      console.error('[PacificaClient] Error creating limit order:', error);
      throw error;
    }
  }

  /**
   * Get market data
   */
  async getMarketData(symbol: string): Promise<MarketData> {
    try {
      const response = await fetch(`${this.baseUrl}/markets/${symbol}`);

      if (!response.ok) {
        throw new Error(`Pacifica API error: ${response.statusText}`);
      }

      const data = (await response.json()) as Record<string, string>;

      return {
        symbol,
        price: parseFloat(data.price),
        volume24h: parseFloat(data.volume24h),
        fundingRate: parseFloat(data.fundingRate),
        openInterest: parseFloat(data.openInterest),
        timestamp: new Date(),
      };
    } catch (error) {
      console.error('[PacificaClient] Error fetching market data:', error);
      throw error;
    }
  }

  /**
   * Get account positions
   */
  async getPositions(walletAddress: string): Promise<any> {
    try {
      const response = await fetch(`${this.baseUrl}/account/positions?account=${walletAddress}`);

      if (!response.ok) {
        throw new Error(`Pacifica API error: ${response.statusText}`);
      }

      return await response.json();
    } catch (error) {
      console.error('[PacificaClient] Error fetching positions:', error);
      throw error;
    }
  }

  /**
   * Get account balance
   */
  async getBalance(walletAddress: string): Promise<number> {
    try {
      const response = await fetch(`${this.baseUrl}/account/balance?account=${walletAddress}`);

      if (!response.ok) {
        throw new Error(`Pacifica API error: ${response.statusText}`);
      }

      const data = (await response.json()) as { totalBalance: string };
      return parseFloat(data.totalBalance);
    } catch (error) {
      console.error('[PacificaClient] Error fetching balance:', error);
      throw error;
    }
  }
}
