import { MarketData } from '../types';

/**
 * Pacifica API Client
 * Handles order creation and market data fetching
 */
export class PacificaClient {
  private baseUrl = 'https://test-api.pacifica.fi/api/v1';

  constructor() {
    // No API key needed - signing is done by wallet
  }

  private async request<T>(path: string, init?: RequestInit): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, init);

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Pacifica API error: ${response.status} ${response.statusText} - ${error}`);
    }

    return (await response.json()) as T;
  }

  /**
   * Create market order
   * Signature must be generated by wallet on frontend
   */
  async createMarketOrder(
    walletAddress: string,
    symbol: string,
    side: 'bid' | 'ask',
    amount: string,
    signature: string,
    timestamp: number,
    agentWallet?: string,
    clientOrderId?: string,
    builderCode?: string
  ): Promise<any> {
    const body = {
      account: walletAddress,
      agent_wallet: agentWallet ?? null,
      signature,
      timestamp,
      expiry_window: 30000,
      symbol,
      side,
      amount,
      slippage_percent: '0.5',
      reduce_only: false,
      client_order_id: clientOrderId,
      builder_code: builderCode,
    };

    try {
      return await this.request('/orders/create_market', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });
    } catch (error) {
      console.error('[PacificaClient] Error creating market order:', error);
      throw error;
    }
  }

  /**
   * Create limit order
   * Signature must be generated by wallet on frontend
   */
  async createLimitOrder(
    walletAddress: string,
    symbol: string,
    side: 'bid' | 'ask',
    amount: string,
    price: string,
    signature: string,
    timestamp: number,
    agentWallet?: string,
    clientOrderId?: string,
    builderCode?: string
  ): Promise<any> {
    const body = {
      account: walletAddress,
      agent_wallet: agentWallet ?? null,
      signature,
      timestamp,
      expiry_window: 30000,
      symbol,
      side,
      amount,
      price,
      tif: 'GTC',
      reduce_only: false,
      client_order_id: clientOrderId,
      builder_code: builderCode,
    };

    try {
      return await this.request('/orders/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });
    } catch (error) {
      console.error('[PacificaClient] Error creating limit order:', error);
      throw error;
    }
  }

  /**
   * Get market data
   */
  async getMarketData(symbol: string): Promise<MarketData> {
    try {
      const data = await this.request<Record<string, string>>(`/markets/${symbol}`);

      return {
        symbol,
        price: parseFloat(data.price),
        volume24h: parseFloat(data.volume24h),
        fundingRate: parseFloat(data.fundingRate),
        openInterest: parseFloat(data.openInterest),
        timestamp: new Date(),
      };
    } catch (error) {
      console.error('[PacificaClient] Error fetching market data:', error);
      throw error;
    }
  }

  /**
   * Get account positions
   */
  async getPositions(walletAddress: string): Promise<any> {
    try {
      return await this.request(`/account/positions?account=${walletAddress}`);
    } catch (error) {
      console.error('[PacificaClient] Error fetching positions:', error);
      throw error;
    }
  }

  /**
   * Get account balance
   */
  async getBalance(walletAddress: string): Promise<number> {
    try {
      const data = await this.request<{ totalBalance: string }>(
        `/account/balance?account=${walletAddress}`
      );
      return parseFloat(data.totalBalance);
    } catch (error) {
      console.error('[PacificaClient] Error fetching balance:', error);
      throw error;
    }
  }

  async approveBuilderCode(
    walletAddress: string,
    signature: string,
    timestamp: number,
    builderCode: string,
    maxFeeRate: string,
    expiryWindow: number = 5000
  ): Promise<any> {
    return this.request('/account/builder_codes/approve', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        account: walletAddress,
        agent_wallet: null,
        signature,
        timestamp,
        expiry_window: expiryWindow,
        builder_code: builderCode,
        max_fee_rate: maxFeeRate,
      }),
    });
  }

  async getBuilderApprovals(walletAddress: string): Promise<any[]> {
    return this.request(`/account/builder_codes/approvals?account=${walletAddress}`);
  }

  async revokeBuilderCode(
    walletAddress: string,
    signature: string,
    timestamp: number,
    builderCode: string,
    expiryWindow: number = 5000
  ): Promise<any> {
    return this.request('/account/builder_codes/revoke', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        account: walletAddress,
        agent_wallet: null,
        signature,
        timestamp,
        expiry_window: expiryWindow,
        builder_code: builderCode,
      }),
    });
  }

  async updateBuilderFeeRate(
    walletAddress: string,
    signature: string,
    timestamp: number,
    builderCode: string,
    feeRate: string,
    expiryWindow: number = 5000
  ): Promise<any> {
    return this.request('/builder/update_fee_rate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        account: walletAddress,
        agent_wallet: null,
        signature,
        timestamp,
        expiry_window: expiryWindow,
        builder_code: builderCode,
        fee_rate: feeRate,
      }),
    });
  }
}
